$PROB TRAP: THIRD DOSE CODED AS STEADY STATE (SS=1) BEFORE STEADY STATE   P:130ss  F:BASE
$INPUT ID TIME AMT ADDL II SS DV MDV EVID
$DATA ../../data/mult-ssx.csv IGNORE=@
$SUBR ADVAN2 TRANS2
$ABBR DERIV2=NO

$PK
  KA = THETA(1) * EXP(ETA(1))
  CL = THETA(2) * EXP(ETA(2))
  V  = THETA(3) * EXP(ETA(3))
  S2 = V

$ERROR
  IPRE = F
  W    = 1
  W    = SQRT(THETA(4)**2 + THETA(5)**2 * IPRE**2)
  IF (W.LT.1E-6) W = 1E-6
  IRES = DV - IPRE
  IWRE = IRES / W
  Y    = IPRE + W * EPS(1)

$THETA
  (0, 1)       ; KA (1/h)
  (0, 3)       ; CL (L/h)
  (0, 40)      ; V  (L)
  (0, 0.05)    ; additive error SD (mg/L)
  (0, 0.1)     ; proportional error CV

$OMEGA
  0.1          ; KA
  0.1          ; CL
  0.05         ; V

$SIGMA 1 FIX

$EST MAX=9999 PRINT=5 METHOD=COND INTER NSIG=3 SIGL=9
     NOABORT NOTBT NOOBT NOSBT
$COV UNCOND PRINT=E
$TAB ID TIME AMT ADDL II SS DV MDV EVID IPRE IWRE CWRES
     ONEHEADER NOPRINT FILE=sdtab
$TAB ID KA CL V ETA1 ETA2 ETA3
     ONEHEADER NOPRINT NOAPPEND FILE=patab
$TAB ID AMT
     ONEHEADER NOPRINT NOAPPEND FILE=cotab
$TAB ID SS
     ONEHEADER NOPRINT NOAPPEND FILE=catab
