$PROB TTE, WEIBULL HAZARD, DOSE EFFECT   P:tte100  F:BASE
$INPUT ID TIME DV MDV EVID DOSE CAVG
$DATA ../../data/tte-sim.csv IGNORE=@
$SUBR ADVAN13 TOL=9
$MODEL COMP=(CUMHAZ)

$PK
  LAM  = THETA(1) * EXP(ETA(1))
  GAM  = THETA(2)
  BETA = THETA(3)
  RH   = EXP(-BETA * DOSE / 100)

$DES
  DADT(1) = LAM * GAM * (T + 1E-9)**(GAM - 1) * RH

$ERROR
  CHZ = A(1)
  SUR = EXP(-CHZ)
  HAZ = LAM * GAM * (TIME + 1E-9)**(GAM - 1) * RH
  IF (DV.EQ.0) Y = SUR
  IF (DV.EQ.1) Y = HAZ * SUR

$THETA
  (0, 0.1)     ; LAM
  (0, 1)       ; GAM, Weibull shape
  (0.5)        ; BETA, log hazard ratio per 100 mg

$OMEGA 0 FIX

$EST MAX=9999 PRINT=5 METHOD=COND LAPLACE LIKELIHOOD NSIG=3 SIGL=9 NOABORT
$COV UNCOND PRINT=E
$TAB ID TIME DV MDV EVID DOSE CAVG CHZ SUR HAZ
     ONEHEADER NOPRINT FILE=sdtab
$TAB ID LAM RH
     ONEHEADER NOPRINT NOAPPEND FILE=patab
$TAB ID CAVG
     ONEHEADER NOPRINT NOAPPEND FILE=cotab
$TAB ID DOSE
     ONEHEADER NOPRINT NOAPPEND FILE=catab
