$PROB PHENO 1COMP IV BOLUS, SAEM THEN IMP EONLY   P:100base  F:BASE
$INPUT ID DAT2=DROP TIME AMT RATE CMT DV MDV EVID
       WT BWT SEX APGR CREA TAFD=DROP
$DATA ../../data/pheno-nm.csv IGNORE=@
$SUBR ADVAN1 TRANS2
$ABBR DERIV2=NO

$PK
  ; MU referencing: each ETA is attached to exactly one MU_n = f(THETA)
  MU_1 = LOG(THETA(1))
  MU_2 = LOG(THETA(2))
  CL   = EXP(MU_1 + ETA(1))
  V    = EXP(MU_2 + ETA(2))
  S1   = V

$ERROR
  IPRE = F
  W    = 1
  W    = SQRT(THETA(3)**2 + THETA(4)**2 * IPRE**2)
  IF (W.LT.1E-6) W = 1E-6
  IRES = DV - IPRE
  IWRE = IRES / W
  Y    = IPRE + W * EPS(1)

$THETA
  (0, 0.0075)  ; CL (L/h)
  (0, 1.5)     ; V  (L)
  (0, 0.6)     ; additive error SD (mg/L)
  (0, 0.12)    ; proportional error CV

$OMEGA BLOCK(2)
  0.3
  0.05  0.3

$SIGMA 1 FIX

$EST METHOD=SAEM INTER NBURN=2000 NITER=1000 ISAMPLE=2 PRINT=200 SIGL=8
     NOABORT SEED=20260917
$EST METHOD=IMP INTER EONLY=1 NITER=5 ISAMPLE=3000 PRINT=1 SEED=20260917
     NOABORT
$COV UNCOND PRINT=E
$TAB ID TIME AMT DV MDV EVID CMT IPRE IWRE CWRES
     ONEHEADER NOPRINT FILE=sdtab
$TAB ID CL V ETA1 ETA2
     ONEHEADER NOPRINT NOAPPEND FILE=patab
$TAB ID WT BWT CREA APGR
     ONEHEADER NOPRINT NOAPPEND FILE=cotab
$TAB ID SEX
     ONEHEADER NOPRINT NOAPPEND FILE=catab
