$PROB COUNT, NEGATIVE BINOMIAL, NO DRUG EFFECT   P:cnt101  F:BASE
$INPUT ID TIME DV MDV DOSE CAVG
$DATA ../../data/cnt-sim.csv IGNORE=@
$PRED
  LAM0 = THETA(1) * EXP(ETA(1))
  OVDP = THETA(2)
  LAM  = LAM0
  R    = 1 / OVDP
  LP1  = GAMLN(DV + R) - GAMLN(DV + 1) - GAMLN(R)
  LP2  = R * LOG(R / (R + LAM)) + DV * LOG(LAM / (R + LAM))
  Y    = -2 * (LP1 + LP2)

$THETA
  (0, 5)       ; LAM0
  (0, 0.2)     ; OVDP

$OMEGA 0.5     ; LAM0

$EST MAX=9999 PRINT=5 METHOD=COND LAPLACE -2LL NSIG=3 SIGL=9 NOABORT
$COV UNCOND PRINT=E
$TAB ID TIME DV MDV DOSE CAVG LAM
     ONEHEADER NOPRINT FILE=sdtab
$TAB ID LAM0 ETA1
     ONEHEADER NOPRINT NOAPPEND FILE=patab
$TAB ID CAVG
     ONEHEADER NOPRINT NOAPPEND FILE=cotab
$TAB ID DOSE
     ONEHEADER NOPRINT NOAPPEND FILE=catab
